### ISSUE TITLE
向老师您请教关于Topcoder - Set Scorecard中开发的小问题

### ISSUE THREAD

**Issue by wentianxin** [skyhit/skyhit.github.io#1]
> 打扰您了。很抱歉在这里提问，因为实在是不知道如何联系您，自己也存在着很大的困惑。倘若老师看到我的问题，希望老师可以在闲余时间中稍微指点学生迷津。

老师您好，我是一名在读大三学生，第一次尝试topcoder组件开发。
看到您今天刚刚提交的 topcoder set scorecard 组件开发的[代码](https://github.com/appirio-tech/direct-app/pull/154)，同时我自己也在做它，但是有几个小疑问 :
1. 老师您是如何得出结论：使用phase的setAttribute字段可以保存scorecard的主键呢？`phase.setAttribute(SCORECARD_ID_PHASE_ATTRIBUTE_KEY,String.valueOf(reviewTemplateId))`
2. 查询 scardcard 列表时，老师又是如何知道可以使用DataAccessor获取scorecard数据呢？`dataAccessor.getData(request).get("get_review_scorecard");` 

是单纯的从代码中分析出来的结论？

**Comment by skyhit** [comment]
不好意思，我是copilot （FireIce）不是那个winner
1. 这个主要是看代码实现吧
2. DataAccessor是TC的一个特有用法，其实是简单的sql query就好了

**Comment by wentianxin** [comment]
恩恩。谢谢您的解答，后来才发现是代码都是由您来提交的。 问题也已经想通了，十分感谢哦。
